---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: default
spec:
  interval: 5m0s
  url: https://bitnami-labs.github.io/sealed-secrets
