---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio
spec:
  releaseName: istio-operator
  dependsOn:
  - name: istio-base
  chart:
    spec:
      chart: ./osdu-istio/istio-operator
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: istio
  values:
    hub: docker.io/istio
    tag: 1.8.2
