---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: default
spec:
  chart:
    spec:
      chart: ./osdu-istio
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: istio-system
  values:
    hub: docker.io/istio
    tag: 1.8.2
    operatorNamespace: istio-operator
