---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio-charts
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: 1.11.4
  url: https://github.com/istio/istio

