---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stamp-environment
  namespace: debug
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: debug
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: ""
    service:
      type: ClusterIP
      port: 80
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    env:
    - name: MESSAGE
      value: Hello World!
    azure:
      enabled: true

