---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-debug
  namespace: debug
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: self-managed-osdu
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: debug
