---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: osdu-base
  namespace: flux-system
spec:
  dependsOn:
  - name: sealed-secrets
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/osdu-base
  prune: true
  validation: client
