---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: osdu-stamp
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/osdu-stamp/
  prune: true
  validation: client
  healthChecks:
  - kind: Deployment
    name: env-debug
    namespace: dev-sample
  # - kind: Deployment
  #   name: istio-operator
  #   namespace: istio
  # - kind: Deployment
  #   name: istiod
  #   namespace: istio
  # - kind: Deployment
  #   name: istio-ingressgateway
  #   namespace: istio
