---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: osdu-azure
  namespace: flux-system
spec:
  dependsOn:
  - name: sealed-secrets
  interval: 5m0s
  path: ./apps/osdu-stamp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

