---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: osdu-istio
  namespace: flux-system
spec:
  dependsOn:
  - name: osdu-base
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/osdu-stamp/istio
  prune: true
  validation: client
  healthChecks:
    - kind: Deployment
      name: istio-operator
      namespace: istio-operator
    - kind: Deployment
      name: istiod
      namespace: istio-system
    - kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
