---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: kube-system
    namespace: sealed-secrets
  interval: 5m0s
  path: ./apps/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  validation: client

