---
# Installation of Sealed Secrets
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: self-managed-osdu-source
  path: ./deploy/sealed-secrets
  prune: true
  validation: client
  healthChecks:
    - kind: Deployment
      name: sealed-secrets
      namespace: kube-system
