---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-services
  namespace: osdu-azure
spec:
  releaseName: core-services
  dependsOn:
  - name: partition-services
  chart:
    spec:
      chart: ./charts/osdu-azure/osdu-core_services
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    azure:
      podIdentityAuthEnabled: false
      oidAuthEnabled: false
    ingress:
      issuer: letsencrypt-prod-dns
      enableKeyvaultCert: false
