---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-services
  namespace: osdu-azure
spec:
  releaseName: core-services
  dependsOn:
  - name: partition-services
  chart:
    spec:
      chart: ./osdu-azure/osdu-core_services
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    azure:
      podIdentityAuthEnabled: false
      oidAuthEnabled: false
    ingress:
      issuer: letsencrypt-prod-dns
      enableKeyvaultCert: false
    configuration:
    - service: indexer-queue
      env:
        - name: AZURE_CLIENT_ID
          secret:
            name: active-directory
            key: principal-clientid
        - name: AZURE_CLIENT_SECRET
          secret:
            name: active-directory
            key: principal-clientpassword

