apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osdu-azure
resources:
  - namespace.yaml
  - partition-services.yaml
  - security-services.yaml
  - core-services.yaml
  - reference-services.yaml
