---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-base
  namespace: osdu-azure
spec:
  releaseName: osdu-base
  dependsOn:
  - name: osdu-base
    namespace: default
  chart:
    spec:
      chart: ./charts/self-managed-osdu-base
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
