{{- range .Values.configuration }}
{{- if .scaledObject }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .service }}-so
  labels:
    deploymentName: {{ .service }}-so
spec:
  scaleTargetRef:
    deploymentName: {{ .service }}
  triggers:
  - type: azure-servicebus
    metadata:
      subscriptionName: {{ .servicebusSubscription }}
      topicName: {{ .servicebusTopic }}
      type: serviceBusTrigger
      direction: in
      name: message
      connection: SERVICE_BUS
{{- end }}
---
{{- end }}
