{{- $serviceType := .Values.service.type }}
{{- $servicePort := .Values.service.port }}
{{- $labels := include "self-managed-osdu.labels" . | nindent 4 }}
{{- $selectorLabels := include "self-managed-osdu.selectorLabels" . | nindent 4 }}
{{- range .Values.configuration }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .service }}
  labels: {{ $labels }}
    app: {{ .service }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ $selectorLabels }}

{{- end }}
