---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-services
  namespace: osdu-azure
spec:
  values:
    replicaCount: 2
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cpljdfe-rhtj-rg
      identity: osdu-self-cpljdfe-rhtj-osdu-identity
      identity_id: eb4baa8e-47f8-43e0-a89e-9dfa863092c1
      keyvault: osdu-self-cpljdf-rhtj-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
    ingress:
      dns: osdu-self-dpljdfe-4zis-gw.centralus.cloudapp.azure.com
