---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 66c8c9d5-6f78-4d7d-8d6a-796a1ae66395
      resourcegroup: osdu-self-ctlbedfb-pa0a-rg
      identity: osdu-self-ctlbedfb-pa0a-osdu-identity
      identity_id: 717844fa-92ac-4a38-8090-e73cdc9ed6f6
      keyvault: osdu-self-ctlbed-pa0a-kv
      appid: 5a4b2404-447d-4e65-bbea-56d973a7b4b5
