---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplcedah-ohay-rg
      identity: osdu-self-cplcedah-ohay-osdu-identity
      identity_id: c56eb193-dadc-43cb-a98f-3de1ae973176
      keyvault: osdu-self-cplced-ohay-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
