---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cpldabdc-wt6m-rg
      identity: osdu-self-cpldabdc-wt6m-osdu-identity
      identity_id: 03b2b09c-14dc-4f1e-a999-468f6b3c58ee
      keyvault: osdu-self-cpldab-wt6m-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
