---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: file-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplcedah-4ya0-gw.centralus.cloudapp.azure.com
    configuration:
    - service: file
      repository: msosdu.azurecr.io/file
      tag: oak
      path: /api/file/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/file/swagger-resources/*"
          - "/api/file/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: file
      - name: server.servlet.contextPath
        value: /api/file/
      - name: server_port
        value: 80
      - name: APPLICATION_PORT
        value: 80
      - name: ACCEPT_HTTP
        value: true
      - name: cosmosdb_database
        value: osdu-db
      - name: LOG_PREFIX
        value: file
      - name: file_spring_logging_level
        value: info
      - name: authorizeAPI
        value: http://entitlements/api/entitlements/v2
      - name: osdu_entitlements_url
        value: http://entitlements/api/entitlements/v2
      - name: osdu_entitlements_app_key
        value: "OBSOLETE"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: SEARCH_HOST
        value: http://search-service/api/search/v2
      - name: JAVA_HEAP_MEMORY
        value: "4096"
      - name: osdu_storage_url
        value: http://storage/api/storage/v2
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_activedirectory_AppIdUri
        value: "api://0ef4dfd1-8adf-441b-aae9-ac7026333520"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: BATCH_SIZE
        value: "100"
      - name: SEARCH_QUERY_LIMIT
        value: "1000"
      - name: event_grid_enabled_status
        value: "true"
      - name: event_grid_topic_status
        value: "statuschangedtopic"
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
