---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/osdu-debug
  - ../base/osdu-base
  - ../base/osdu-istio
  - ../base/osdu-airflow
patchesStrategicMerge:
  - osdu-debug-values.yaml
  - osdu-istio-values.yaml
  - osdu-airflow-values.yaml
