---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dev-sample
  - ../base/osdu-base
  - ../base/osdu-istio
  - ../base/osdu-azure
  - ../base/osdu-airflow
patchesStrategicMerge:
  - dev-sample-values.yaml
  - osdu-istio-values.yaml
  - partition-services-values.yaml
  - security-services-values.yaml
  - core-services-values.yaml
  - reference-services-values.yaml
  - osdu-airflow-values.yaml
