---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  dependsOn:
  - name: istio-operator
  chart:
    spec:
      chart: ./osdu-istio
      sourceRef:
        kind: GitRepository
        name: helm-charts-azure
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: istio-system
  global:
    values:
      azure:
        tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
        appid: 5a4b2404-447d-4e65-bbea-56d973a7b4b5
