---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    ################################################################################
    # Specify the azure environment specific values
    #
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 66c8c9d5-6f78-4d7d-8d6a-796a1ae66395
      resourcegroup: osdu-self-ctlbedfb-pa0a-rg
      identity: osdu-self-ctlbedfb-pa0a-osdu-identity
      identity_id: 717844fa-92ac-4a38-8090-e73cdc9ed6f6
      keyvault: osdu-self-ctlbed-pa0a-kv
      appid: 5a4b2404-447d-4e65-bbea-56d973a7b4b5

    ################################################################################
    # Specify any optional override values
    #
    airflowLogin:
      name: admin                 #<-- Default Airflow Web UI username

    ################################################################################
    # Specify the airflow configuration override values
    #
    airflow:
      ingress:
        host: osdu-self-dplbedfb-wrt3-gw.centralus.cloudapp.azure.com           #<-- Set this to false to disable Admin UI ingress
        web:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-dns
            # Please uncomment below two lines and comment above line to use your own certificate from keyvault
            #cert-manager.io/cluster-issuer: null
            #appgw.ingress.kubernetes.io/appgw-ssl-certificate: "appgw-ssl-cert"
          host: osdu-self-dplbedfb-wrt3-gw.centralus.cloudapp.azure.com
          tls:
            enabled: true    #<-- Set this to false to enable keyvault certificate
      externalDatabase:
        host: osdu-self-dplbedfb-wrt3-pg.postgres.database.azure.com
        user:  osdu_admin@osdu-self-dplbedfb-wrt3-pg
      externalRedis:
        host: osdu-self-dplbedfb-wrt3-cache.redis.cache.windows.net

      # The namespace needs to be set to where Airflow has been installed.
      airflow:
        extraEnv:
          - name: CLOUD_PROVIDER
            value: "azure"
          - name: AIRFLOW_VAR_KEYVAULT_URI
            valueFrom:
              configMapKeyRef:
                name: osdu-svc-config
                key: ENV_KEYVAULT
          - name: AIRFLOW__CORE__FERNET_KEY
            valueFrom:
              secretKeyRef:
                name: airflow
                key: fernet-key
          - name: AIRFLOW_CONN_AZ_LOG
            valueFrom:
              secretKeyRef:
                name: airflow
                key: remote-log-connection
          - name: AIRFLOW_VAR_AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: active-directory
                key: tenantid
          - name: AIRFLOW_VAR_AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: active-directory
                key: principal-clientid
          - name: AIRFLOW_VAR_AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: active-directory
                key: principal-clientpassword
          - name: AIRFLOW_VAR_AAD_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: active-directory
                key: application-appid
          - name: AIRFLOW_VAR_APPINSIGHTS_KEY
            valueFrom:
              secretKeyRef:
                name: central-logging
                key: appinsights
          - name: AIRFLOW_VAR_AZURE_DNS_HOST
            value: osdu-self-dplbedfb-wrt3-gw.centralus.cloudapp.azure.com
          - name: AIRFLOW_VAR_AZURE_ENABLE_MSI
            value:
          # Needed for installing python osdu python sdk. In future this will be changed
          - name: CI_COMMIT_TAG
            value: "v0.11.0"
          - name: AIRFLOW_VAR_ENTITLEMENTS_MODULE_NAME
            value: "entitlements_client"
          - name: AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH
            value: "/opt/airflow/dags/configs/dataload.ini"
          - name: AIRFLOW_VAR_CORE__SERVICE__SCHEMA__URL
            value:  "http://schema.osdu-azure.svc.cluster.local/api/schema-service/v1/schema"
          - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH__URL
            value: "http://search.osdu-azure.svc.cluster.local/api/search/v2/query"
          - name: AIRFLOW_VAR_CORE__SERVICE__STORAGE__URL
            value:  "http://storage.osdu-azure.svc.cluster.local/api/storage/v2/records"
          - name: AIRFLOW_VAR_CORE__SERVICE__FILE__HOST
            value: "http://file.osdu-azure.svc.cluster.local/api/file/v2"
          - name: AIRFLOW_VAR_CORE__SERVICE__WORKFLOW__HOST
            value: "http://workflow.osdu-azure.svc.cluster.local/api/workflow"
          - name: AIRFLOW_VAR_CORE__SERVICE__SEARCH_WITH_CURSOR__URL
            value: "http://search.osdu-azure.svc.cluster.local/api/search/v2/query_with_cursor"
        extraConfigmapMounts:
            - name: remote-log-config
              mountPath: /opt/airflow/config
              configMap: airflow-remote-log-config
              readOnly: true
        extraPipPackages: [
            "flask-bcrypt==0.7.1",
            "apache-airflow[statsd]",
            "apache-airflow[kubernetes]",
            "apache-airflow-backport-providers-microsoft-azure==2021.2.5",
            "dataclasses==0.8",
            "google-cloud-storage",
            "python-keycloak==0.24.0",
            "msal==1.9.0",
            "azure-identity==1.5.0",
            "azure-keyvault-secrets==4.2.0",
            "azure-storage-blob",
            "azure-servicebus==7.0.1",
            "toposort==1.6",
            "strict-rfc3339==0.7",
            "jsonschema==3.2.0",
            "pyyaml==5.4.1",
            "requests==2.25.1",
            "tenacity==8.0.1",
            "https://azglobalosdutestlake.blob.core.windows.net/pythonsdk/osdu_api-0.11.0.tar.gz",
            "https://azglobalosdutestlake.blob.core.windows.net/pythonsdk/osdu_airflow-0.0.1.tar.gz"
        ]
        extraVolumeMounts:
            - name: azure-keyvault
              mountPath: "/mnt/azure-keyvault"
              readOnly: true
            - name: dags-data
              mountPath: /opt/airflow/plugins
              subPath: plugins
        extraVolumes:
            - name: azure-keyvault
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: azure-keyvault
