---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cpljdfe-1jmb-rg
      identity: osdu-self-cpljdfe-1jmb-osdu-identity
      identity_id: 2259ca26-7f53-467d-b55f-3321b8aa494c
      keyvault: osdu-self-cpljdf-1jmb-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
    airflowLogin:
      name: admin
    airflow:
      ingress:
        host: osdu-self-dpljdfe-nsin-gw.centralus.cloudapp.azure.com
        web:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod-dns
          host: osdu-self-dpljdfe-nsin-gw.centralus.cloudapp.azure.com
      externalDatabase:
        host: osdu-self-dpljdfe-nsin-pg.postgres.database.azure.com
        user:  osdu_admin@osdu-self-dpljdfe-nsin-pg
      externalRedis:
        host: osdu-self-dpljdfe-nsin-cache.redis.cache.windows.net
      airflow:
        extraEnv:
          - name: AIRFLOW_VAR_AZURE_DNS_HOST
            value: "osdu-self-dpljdfe-nsin-gw.centralus.cloudapp.azure.com"
