---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partition-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dpldabdc-gs7m-gw.centralus.cloudapp.azure.com
    configuration:
    - service: partition
      repository: msosdu.azurecr.io/partition
      tag: oak
      path: /api/partition/v1/*
      probe: /api/partition/v1/swagger-ui.html
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v1/api-docs"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "*/swagger"
          - "*/swagger-ui.html"
          - "*/swagger-resources"
          - "/api/partition/v1/swagger-resources/*"
          - "/api/partition/v1/webjars/*"
          - "*/actuator/health"
          - "*/_ah/**"
      env:
      - name: spring_application_name
        value: partition
      - name: server.servlet.contextPath
        value: /api/partition/v1/
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: azure_activedirectory_AppIdUri
        value: "api://0ef4dfd1-8adf-441b-aae9-ac7026333520"
      - name: azure_activedirectory_session_stateless
        value: "false"
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: azure_istioauth_enabled
        value: "true"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: REDIS_DATABASE
        config:
          name: osdu-svc-config
          key: REDIS_DB_PARTITION
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
