---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplbcgdb-78uy-rg
      identity: osdu-self-cplbcgdb-78uy-osdu-identity
      identity_id: a7f62831-4571-4489-8782-1b9f8cb35062
      keyvault: osdu-self-cplbcg-78uy-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "4Gi"
      defaultCpuLimits: "1"
      defaultMemoryLimits: "4Gi"
    identity:
      name: osdu-identity
