---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplcedah-hojv-rg
      identity: osdu-self-cplcedah-hojv-osdu-identity
      identity_id: 69b28cb6-c26f-47d6-8739-218e67813f52
      keyvault: osdu-self-cplced-hojv-kv
      appid: 0ef4dfd1-8adf-441b-aae9-ac7026333520
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "4Gi"
      defaultCpuLimits: "1"
      defaultMemoryLimits: "4Gi"
    identity:
      name: osdu-identity
