---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplhacb-udmg-rg
      identity: osdu-self-cplhacb-udmg-osdu-identity
      identity_id: 6db0097b-05f1-4ab5-a9ac-ebc68a97d756
      keyvault: osdu-self-cplhac-udmg-kv
      appid: 986292aa-2ecd-4d87-a7dc-e24b92e501bc
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "4Gi"
      defaultCpuLimits: "1"
      defaultMemoryLimits: "4Gi"
    identity:
      name: osdu-identity
