---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 2e458de2-af10-484c-a5a5-6c259d9a907f
      resourcegroup: osdu-self-cplceicj-ax8o-rg
      identity: osdu-self-cplceicj-ax8o-osdu-identity
      identity_id: 61d9889d-c83b-4407-9966-4ea084daf4fa
      keyvault: osdu-self-cplcei-ax8o-kv
      appid: 986292aa-2ecd-4d87-a7dc-e24b92e501bc
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "4Gi"
      defaultCpuLimits: "1"
      defaultMemoryLimits: "4Gi"
    identity:
      name: osdu-identity
