name: '3. Deploy Infrastructure'

on:
  workflow_dispatch:

env:
  AZURE_PRINCIPAL_NAME: osdu-azure-credentials
  OSDU_PRINCIPAL_NAME: osdu-credentials
  OSDU_APPLICATION_NAME: osdu-application

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: infrastructure:latest
        outputs: type=docker,dest=/tmp/infrastructure.tar

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v2
      with:
        name: infrastructure
        path: /tmp/infrastructure.tar

  central-reources:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: infrastructure
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/infrastructure.tar
          docker image ls -a
