name: '3. Deploy Infrastructure'

on:
  workflow_dispatch:

env:
  AZURE_PRINCIPAL_NAME: osdu-azure-credentials
  OSDU_PRINCIPAL_NAME: osdu-credentials
  OSDU_APPLICATION_NAME: osdu-application

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        build-args: SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY }}, SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
        tags: self-managed-osdu:latest
        outputs: type=docker,dest=/tmp/self-managed-osdu.tar

    - name: Upload Docker Image Artifact
      uses: actions/upload-artifact@v2
      with:
        name: self-managed-osdu
        path: /tmp/self-managed-osdu.tar

  central-reources:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: self-managed-osdu
          path: /tmp

      - name: Load image
        run: |
          echo ${{ secrets.ENV_FILE }} > /tmp/.env
          docker load --input /tmp/self-managed-osdu.tar
          docker run self-managed-osdu:latest --env TF_VAR_workspace="cr-${{ secrets.RAND }} --workdir /osdu-azure/templates/osdu-r3-mvp/central_resources
          rm /tmp/.env
