name: '4. Stamp Configure'

on:
  workflow_dispatch:

env:
  OSDU_VERSION: v0.11.0

jobs:

  flux-setup:
    name: Gitops Configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      CLUSTER: osdu-stamp

    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Environment Settings
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            ENV_CLUSTER=$(az aks list --resource-group $GROUP --query [].name -otsv)
            echo "CLUSTER_RESOURCE_GROUP=$GROUP" >> $GITHUB_ENV
            echo "CLUSTER_NAME=$ENV_CLUSTER" >> $GITHUB_ENV

      - name: AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Install Flux
        run: curl -s https://fluxcd.io/install.sh | bash;

      - name: Bootstrap Flux
        run: flux bootstrap github --owner=${{ github.repository_owner }} --repository=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2	) --branch=main --path=./clusters/${{ env.CLUSTER }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Flux Source(s) & Kustomization(s)
        run: |
          flux create source git self-managed-osdu-source \
            --url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
            --interval 1m \
            --branch main \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/self-managed-osdu-source.yaml

          flux create source git helm-charts-azure-source \
            --url https://community.opengroup.org/osdu/platform/deployment-and-operations/helm-charts-azure \
            --interval 1m \
            --branch master \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/helm-charts-azure-source.yaml

          flux create kustomization sealed-secrets \
            --source=flux-system \
            --path=./apps/sealed-secrets \
            --prune=true \
            --interval=5m \
            --validation=client \
            --health-check="Deployment/kube-system.sealed-secrets" \
            --health-check-timeout=3m \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/sealed-secrets-kustomization.yaml

          flux create kustomization osdu-azure \
            --source=flux-system \
            --path=./apps/$CLUSTER \
            --prune=true \
            --interval=5m \
            --depends-on=sealed-secrets \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/osdu-azure-kustomization.yaml


      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Initialize Software Install'
          add: 'clusters'
