name: '4. Stamp Configure'

on:
  workflow_dispatch:

env:
  OSDU_VERSION: v0.11.0
  CLUSTER: osdu-stamp

jobs:

  flux-setup:
    name: Gitops Configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}

    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Environment Settings
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            ENV_CLUSTER=$(az aks list --resource-group $GROUP --query [].name -otsv)
            echo "CLUSTER_RESOURCE_GROUP=$GROUP" >> $GITHUB_ENV
            echo "CLUSTER_NAME=$ENV_CLUSTER" >> $GITHUB_ENV

      - name: AKS Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Install Flux
        run: curl -s https://fluxcd.io/install.sh | bash;

      - name: Bootstrap Flux
        run: flux bootstrap github --owner=${{ github.repository_owner }} --repository=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2	) --branch=main --path=./clusters/${{ env.CLUSTER }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Cluster Directories
        run: |
          mkdir -p $GITHUB_WORKSPACE/clusters/$CLUSTER
          mkdir -p $GITHUB_WORKSPACE/apps/$CLUSTER/istio
          mkdir -p $GITHUB_WORKSPACE/apps/$CLUSTER/airflow

      - name: Define Flux Sources
        run: |
          flux create source git self-managed-osdu \
            --url $GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
            --interval 1m \
            --branch main \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/self-managed-osdu.yaml

          flux create source git helm-charts-azure \
            --url https://community.opengroup.org/osdu/platform/deployment-and-operations/helm-charts-azure \
            --interval 1m \
            --branch master \
            --export > $GITHUB_WORKSPACE/clusters/$CLUSTER/helm-charts-azure.yaml

      - name: sealed-secrets
        run: |
          cat > $GITHUB_WORKSPACE/clusters/$CLUSTER/sealed-secrets.yaml <<EOF
          ---
          apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
          kind: Kustomization
          metadata:
            name: sealed-secrets
            namespace: flux-system
          spec:
            interval: 5m0s
            sourceRef:
              kind: GitRepository
              name: self-managed-osdu
            path: ./apps/base/sealed-secrets
            prune: true
            validation: client
            healthChecks:
              - kind: Deployment
                name: sealed-secrets
                namespace: kube-system
          EOF

      - name: osdu-base
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'ctl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

            cat > $GITHUB_WORKSPACE/clusters/$CLUSTER/osdu-base.yaml << EOF
            ---
            apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
            kind: Kustomization
            metadata:
              name: osdu-base
              namespace: flux-system
            spec:
              dependsOn:
              - name: sealed-secrets
              interval: 5m0s
              sourceRef:
                kind: GitRepository
                name: flux-system
              path: ./apps/base/osdu-base
              prune: true
              validation: client
            EOF


      - name: osdu-istio
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'ctl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

            cat > $GITHUB_WORKSPACE/clusters/$CLUSTER/osdu-istio.yaml << EOF
            ---
            apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
            kind: Kustomization
            metadata:
              name: osdu-istio
              namespace: flux-system
            spec:
              dependsOn:
              - name: osdu-base
              interval: 5m0s
              sourceRef:
                kind: GitRepository
                name: flux-system
              path: ./apps/$CLUSTER/istio
              prune: true
              validation: client
              healthChecks:
              - kind: Deployment
                name: istio-operator
                namespace: istio-operator
              - kind: Deployment
                name: istiod
                namespace: istio-system
              - kind: Deployment
                name: istio-ingressgateway
                namespace: istio-system
            EOF

            cat > $GITHUB_WORKSPACE/apps/$CLUSTER/istio/kustomization.yaml << EOF
            ---
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization
            resources:
              - ../../base/osdu-istio
            patchesStrategicMerge:
              - override-values.yaml
            EOF

            cat > $GITHUB_WORKSPACE/apps/$CLUSTER/istio/override-values.yaml << EOF
            ---
            apiVersion: helm.toolkit.fluxcd.io/v2beta1
            kind: HelmRelease
            metadata:
              name: osdu-istio
              namespace: istio-system
            spec:
              values:
                global:
                  azure:
                    tenant: $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/tenant-id --query value -otsv)
                    appid: $(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/aad-client-id --query value -otsv)
            EOF

      - name: osdu-airflow
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'ctl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

            cat > $GITHUB_WORKSPACE/clusters/$CLUSTER/osdu-airflow.yaml << EOF
            ---
            apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
            kind: Kustomization
            metadata:
              name: osdu-airflow
              namespace: flux-system
            spec:
              dependsOn:
              - name: osdu-base
              interval: 5m0s
              sourceRef:
                kind: GitRepository
                name: flux-system
              path: ./apps/$CLUSTER/airflow
              prune: true
              validation: client
            EOF

      - name: GitOps Commit
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Initialize Software Install'
          add: '.'
