name: 'Stuff'

on:
  workflow_dispatch:

jobs:

  cosmos-data:
    name: Load Data - TenantInfo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip azure-cosmos

      - name: Load Record
        env:
          PARTITION_NAME: opendes
        run: |
          GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
          ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

          export COSMOS_ENDPOINT=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/${PARTITION_NAME}-cosmos-endpoint --query value -otsv)
          export COSMOS_KEY=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/${PARTITION_NAME}-cosmos-primary-key --query value -otsv)
          export SERVICE_PRINCIPAL_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-username --query value -otsv)
          export SERVICE_PRINCIPAL_OID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-id --query value -otsv)

          python3 scripts/upload-data.py


  partition-data:
    name: Load Data - PartitionInfo
    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload Partition Info
        env:
          TABLE: PartitionInfo
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)
            STORAGE_NAME=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage --query value -otsv)
            STORAGE_KEY=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/airflow-storage-key --query value -otsv)

            TIME=$(date +"%Y-%m-%dT%H:%M:%S.NZ")
            echo $TIME

            az storage entity insert --account-name $STORAGE_NAME --account-key $STORAGE_KEY --table-name $PartitionInfo \
              --entity PartitionKey=opendes RowKey=compliance-ruleset TIMESTAMP=$TIME SENSITIVE=false VALUE=shared --if-exists replace

            # PARTITIONKEY  ROWKEY              TIMESTAMP                     SENSITIVE   VALUE
            # opendes       compliance-ruleset  2021-03-01T20:36:57.1474948Z  false       shared
