name: 'Stuff'

on:
  workflow_dispatch:

jobs:

  cosmos-data:
    name: Load Cosmos Data - Tenant Info
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve Stamp Env Variables
        env:
          PARTITION_NAME: opendes
        run: |
          GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
          ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

          echo "GROUP=$GROUP" >> $GITHUB_ENV
          echo "ENV_VAULT=$ENV_VAULT" >> $GITHUB_ENV

          export COSMOS_ENDPOINT=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/${PARTITION_NAME}-cosmos-endpoint --query value -otsv)
          export COSMOS_KEY=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/${PARTITION_NAME}-cosmos-primary-key --query value -otsv)
          export SERVICE_PRINCIPAL_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-username --query value -otsv)
          export SERVICE_PRINCIPAL_OID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-id --query value -otsv)

      - name: Check
        run: echo $SERVICE_PRINCIPAL_OID

      - name: Install dependencies
        run: python -m pip install --upgrade pip azure-cosmos

      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            from azure.cosmos import CosmosClient, PartitionKey
            import json
            import pprint
            import os
            import time

            print("Directory contents:")
            for f in os.listdir():
              print(f)



      # - uses: jannekem/run-python-script-action@v1
      #   with:
      #     script: |
      #       import os
      #       print("Directory contents:")
      #       for f in os.listdir():
      #           print(f)
